//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositePeriodMonitor", Namespace="http://schemas.datacontract.org/2004/07/Monitoring")]
    [System.SerializableAttribute()]
    public partial class CompositePeriodMonitor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberClientRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberClientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberRequestsGoogleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberRequestsVelibField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberClientRequests {
            get {
                return this.NumberClientRequestsField;
            }
            set {
                if ((this.NumberClientRequestsField.Equals(value) != true)) {
                    this.NumberClientRequestsField = value;
                    this.RaisePropertyChanged("NumberClientRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberClients {
            get {
                return this.NumberClientsField;
            }
            set {
                if ((this.NumberClientsField.Equals(value) != true)) {
                    this.NumberClientsField = value;
                    this.RaisePropertyChanged("NumberClients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberRequestsGoogle {
            get {
                return this.NumberRequestsGoogleField;
            }
            set {
                if ((this.NumberRequestsGoogleField.Equals(value) != true)) {
                    this.NumberRequestsGoogleField = value;
                    this.RaisePropertyChanged("NumberRequestsGoogle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberRequestsVelib {
            get {
                return this.NumberRequestsVelibField;
            }
            set {
                if ((this.NumberRequestsVelibField.Equals(value) != true)) {
                    this.NumberRequestsVelibField = value;
                    this.RaisePropertyChanged("NumberRequestsVelib");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompositePeriodMonitor", ReplyAction="http://tempuri.org/IService1/GetCompositePeriodMonitorResponse")]
        WcfServiceLibrary.ServiceReference1.CompositePeriodMonitor GetCompositePeriodMonitor(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompositePeriodMonitor", ReplyAction="http://tempuri.org/IService1/GetCompositePeriodMonitorResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary.ServiceReference1.CompositePeriodMonitor> GetCompositePeriodMonitorAsync(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberClients", ReplyAction="http://tempuri.org/IService1/GetNumberClientsResponse")]
        int GetNumberClients(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberClients", ReplyAction="http://tempuri.org/IService1/GetNumberClientsResponse")]
        System.Threading.Tasks.Task<int> GetNumberClientsAsync(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberClientRequests", ReplyAction="http://tempuri.org/IService1/GetNumberClientRequestsResponse")]
        int GetNumberClientRequests(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberClientRequests", ReplyAction="http://tempuri.org/IService1/GetNumberClientRequestsResponse")]
        System.Threading.Tasks.Task<int> GetNumberClientRequestsAsync(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberRequestsVelib", ReplyAction="http://tempuri.org/IService1/GetNumberRequestsVelibResponse")]
        int GetNumberRequestsVelib(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberRequestsVelib", ReplyAction="http://tempuri.org/IService1/GetNumberRequestsVelibResponse")]
        System.Threading.Tasks.Task<int> GetNumberRequestsVelibAsync(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberRequestsGoogle", ReplyAction="http://tempuri.org/IService1/GetNumberRequestsGoogleResponse")]
        int GetNumberRequestsGoogle(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberRequestsGoogle", ReplyAction="http://tempuri.org/IService1/GetNumberRequestsGoogleResponse")]
        System.Threading.Tasks.Task<int> GetNumberRequestsGoogleAsync(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentAverageDelay", ReplyAction="http://tempuri.org/IService1/GetCurrentAverageDelayResponse")]
        double GetCurrentAverageDelay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentAverageDelay", ReplyAction="http://tempuri.org/IService1/GetCurrentAverageDelayResponse")]
        System.Threading.Tasks.Task<double> GetCurrentAverageDelayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNumberClients", ReplyAction="http://tempuri.org/IService1/UpdateNumberClientsResponse")]
        void UpdateNumberClients(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNumberClients", ReplyAction="http://tempuri.org/IService1/UpdateNumberClientsResponse")]
        System.Threading.Tasks.Task UpdateNumberClientsAsync(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNumberClientRequests", ReplyAction="http://tempuri.org/IService1/UpdateNumberClientRequestsResponse")]
        void UpdateNumberClientRequests(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNumberClientRequests", ReplyAction="http://tempuri.org/IService1/UpdateNumberClientRequestsResponse")]
        System.Threading.Tasks.Task UpdateNumberClientRequestsAsync(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNumberRequestsVelib", ReplyAction="http://tempuri.org/IService1/UpdateNumberRequestsVelibResponse")]
        void UpdateNumberRequestsVelib(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNumberRequestsVelib", ReplyAction="http://tempuri.org/IService1/UpdateNumberRequestsVelibResponse")]
        System.Threading.Tasks.Task UpdateNumberRequestsVelibAsync(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNumberRequestsGoogle", ReplyAction="http://tempuri.org/IService1/UpdateNumberRequestsGoogleResponse")]
        void UpdateNumberRequestsGoogle(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNumberRequestsGoogle", ReplyAction="http://tempuri.org/IService1/UpdateNumberRequestsGoogleResponse")]
        System.Threading.Tasks.Task UpdateNumberRequestsGoogleAsync(int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCurrentAverageDelay", ReplyAction="http://tempuri.org/IService1/UpdateCurrentAverageDelayResponse")]
        void UpdateCurrentAverageDelay(double delay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCurrentAverageDelay", ReplyAction="http://tempuri.org/IService1/UpdateCurrentAverageDelayResponse")]
        System.Threading.Tasks.Task UpdateCurrentAverageDelayAsync(double delay);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfServiceLibrary.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfServiceLibrary.ServiceReference1.IService1>, WcfServiceLibrary.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceLibrary.ServiceReference1.CompositePeriodMonitor GetCompositePeriodMonitor(int period) {
            return base.Channel.GetCompositePeriodMonitor(period);
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary.ServiceReference1.CompositePeriodMonitor> GetCompositePeriodMonitorAsync(int period) {
            return base.Channel.GetCompositePeriodMonitorAsync(period);
        }
        
        public int GetNumberClients(int period) {
            return base.Channel.GetNumberClients(period);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberClientsAsync(int period) {
            return base.Channel.GetNumberClientsAsync(period);
        }
        
        public int GetNumberClientRequests(int period) {
            return base.Channel.GetNumberClientRequests(period);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberClientRequestsAsync(int period) {
            return base.Channel.GetNumberClientRequestsAsync(period);
        }
        
        public int GetNumberRequestsVelib(int period) {
            return base.Channel.GetNumberRequestsVelib(period);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberRequestsVelibAsync(int period) {
            return base.Channel.GetNumberRequestsVelibAsync(period);
        }
        
        public int GetNumberRequestsGoogle(int period) {
            return base.Channel.GetNumberRequestsGoogle(period);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberRequestsGoogleAsync(int period) {
            return base.Channel.GetNumberRequestsGoogleAsync(period);
        }
        
        public double GetCurrentAverageDelay() {
            return base.Channel.GetCurrentAverageDelay();
        }
        
        public System.Threading.Tasks.Task<double> GetCurrentAverageDelayAsync() {
            return base.Channel.GetCurrentAverageDelayAsync();
        }
        
        public void UpdateNumberClients(int period) {
            base.Channel.UpdateNumberClients(period);
        }
        
        public System.Threading.Tasks.Task UpdateNumberClientsAsync(int period) {
            return base.Channel.UpdateNumberClientsAsync(period);
        }
        
        public void UpdateNumberClientRequests(int period) {
            base.Channel.UpdateNumberClientRequests(period);
        }
        
        public System.Threading.Tasks.Task UpdateNumberClientRequestsAsync(int period) {
            return base.Channel.UpdateNumberClientRequestsAsync(period);
        }
        
        public void UpdateNumberRequestsVelib(int period) {
            base.Channel.UpdateNumberRequestsVelib(period);
        }
        
        public System.Threading.Tasks.Task UpdateNumberRequestsVelibAsync(int period) {
            return base.Channel.UpdateNumberRequestsVelibAsync(period);
        }
        
        public void UpdateNumberRequestsGoogle(int period) {
            base.Channel.UpdateNumberRequestsGoogle(period);
        }
        
        public System.Threading.Tasks.Task UpdateNumberRequestsGoogleAsync(int period) {
            return base.Channel.UpdateNumberRequestsGoogleAsync(period);
        }
        
        public void UpdateCurrentAverageDelay(double delay) {
            base.Channel.UpdateCurrentAverageDelay(delay);
        }
        
        public System.Threading.Tasks.Task UpdateCurrentAverageDelayAsync(double delay) {
            return base.Channel.UpdateCurrentAverageDelayAsync(delay);
        }
    }
}
